
all:
	npx tsc

clean:
	rm -f namematching.js

dist-clean:
	rm -rf node_modules 

install:
	npm install --save-dev typescript @types/node
	npm install --save-dev @types/aws-lambda
	npm install --save-dev @types/fast-levenshtein
	npm install axios
	npm install csv-parse
	npm install fs


